### ISSUE TITLE
Rich metadata

### ISSUE THREAD

**Issue by makxdekkers** [RDA-FAIR/FAIR-data-maturity-model-WG#13]
Which indicators should be related to ‘rich metadata’? There are different requirements for metadata for discovery (for a user to be able to find relevant data) and for reuse (for a reuser to be able to understand how the data was produced and how it can be reused).

**Comment by makxdekkers** [comment]
Could it be helpful to think in the direction taken by the [DataCite Metadata Kernel ](https://schema.datacite.org/meta/kernel-4.2/doc/DataCite-MetadataKernel_v4.2.pdf), or the [EU DCAT Application Profile](https://joinup.ec.europa.eu/release/dcat-ap/121) on Mandatory, Recommended and Optional metadata properties?

**Comment by keithjeffery** [comment]
I would suggest that richer metadata than those indicated are required.  See RDA MIG work on elements https://www.rd-alliance.org/groups/metadata-ig.html
Also while the metadata elements required for F, A, I, R are different there is a very large intersection in my experience.

**Comment by makxdekkers** [comment]
In a [message to the WG](https://www.rd-alliance.org/group/fair-data-maturity-model-wg/post/fair-data-maturity-model-indicators), I solicted feedback from the WG on the proposal to adopt the set of metadata elements proposed by the RDA Metadata Interest Group.

**Comment by makxdekkers** [comment]
@keithjeffery It is indeed the case that there is overlap between the metadata aspects across the FAIR principles. In order to come to relevant indicators for 'rich metadata', there could be two approaches:
1. assign indicators for specific elements of the element set to the principles where they are most relevant, e.g. description to F2 (https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/16), provenance to R1.1 (https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/28) etc., or
2. create a single indicator, e.g. in R1 (https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/26) as this principle seems to provide a catch-all: "_richly described with a plurality of accurate and relevant attributes_".

**Comment by keithjeffery** [comment]
Although more work I would suggest option 1.  This would demonstrate the degree of intersection.  It would also ensure that any claim that a resource was FAIR for some of the principles but not others was justified.  Option 2 would mean that a resource could be claimed as FAIR except for R1 indicating it was FAIR for F, A, I when in fact it would not be.

**Comment by makxdekkers** [comment]
Understood. Could you, or the RDA MIG, propose a distribution of the MIG elements over the FAIR principles?

**Comment by keithjeffery** [comment]
I'll do a first draft over the next day or so and post here for comment/discussion - OK?

**Comment by makxdekkers** [comment]
Perfect!

**Comment by keithjeffery** [comment]
Actually I did it quite quickly as a first proposal relaitonship for discussion.  In essence,  the relationship of F2 to the elements defines the optimim I think.  Spreadsheet attached.
[RDA MIG Elements to FAIR Principles 20190707.xlsx](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/files/3365515/RDA.MIG.Elements.to.FAIR.Principles.20190707.xlsx)

**Comment by makxdekkers** [comment]
Thanks Keith, that was quick! I do understand that your mapping links a metadata element to all the principles to which it is important, but having the 'unique identifier' linked to all principles is maybe a bit too much; it  would not make much sense, in my opinion, to have an indicator for the identifier for each and every principle. Could we maybe try to identify the one principle that is most important for an element and where it should be tested? For example, the element 'unique identifier' should be an indicator for F1 -- if it is tested (pass/fail) for that principle, there's no need to test it again and again.

**Comment by keithjeffery** [comment]
Makx –
It was quick because – of course- I have been thinking about the relationship between MIG elements and FAIR or some time.
To your point, it assumes that FAIRNESS is tested starting at F1 and moving across A,I,R.  If you started somewhere else (e.g. R1) then if Universally Unique Eternally Persistent ID is not mandatory/tested is it still FAIR?
Hence I put ID ad URL as mandatory throughout as a minimum.
My personal view is that it would be simpler to reproduce the cells for F2 throughout but I accept that many cells under each principle would be redundant interpreting the FAIR principle strictly – although the implied presence of that metadata element would be useful in ‘backing up / making comprehensible’ the use of metadata element instances to support the principle.
Best
Keith
--------------------------------------------------------------------------------
Keith G Jeffery Consultants
Prof Keith G Jeffery
E: keith.jeffery@keithgjefferyconsultants.co.uk<mailto:keith.jeffery@keithgjefferyconsultants.co.uk>
T: +44 7768 446088
S: keithgjeffery
----------------------------------------------------------------------------------------------------------------------------------
The contents of this email are sent in confidence for the use of the
intended recipient only.  If you are not one of the intended
recipients do not take action on it or show it to anyone else, but
return this email to the sender and delete your copy of it.
----------------------------------------------------------------------------------------------------------------------------------

**Comment by makxdekkers** [comment]
@keithjeffery I am not sure that there is an issue with where the evaluation starts -- in my mind, an evaluation of FAIRness needs to consider all principles and indicators, in whatever order you like. If you start with R1, and only evaluate R1, the only thing you can say is that the resource is FAIR as far as R1 is concerned.
So rather than 'reproducing the cells for F2' for all principles, I would still say that the choice is testing all metadata elements under F2 or R1, or distributing the metadata elements over the principles where they are most important.

For example:

- 'unique identifier': existence in F1, inclusion in metadata in F3
- 'location (URL)': F2 or A1
- 'description': F2

etc.

**Comment by keithjeffery** [comment]
Makx -
I did not respond immediately but thought about it overnight.  The point we are discussing relates directly to how one measures FAIRness.  The implication of your approach is 'all or nothing'; that is an asset has to meet all the criteria/metrics (although some may be advisory rather than mandatory) to be FAIR.  I was considering that an asset may be FAIR in F,A but not in I,R.  I think in the FAIR principles there is am underlying assumption of  progression i.e. F-A-I-R and I suspect we can all agree that it is easier to make an asset F-FAIR than R-FAIR.  I have been wondering - for example - if it is posible to be I-FAIR and not F-FAIR.

The fact that R1 to some extent is closely related to F2 would seem to indicate that the principles each should be stand alone and not dependent upon another (previous?) principle being already satisfied as FAIR by an asset.  However, this is the only such example and on the other hand, if any principle in A,I,R is taken stand-alone without the principles of F then it would be impossible to implement in a FAIR way.

Thus I come round to the idea that FAIRness  can only be asserted (a) in totality or (b) covering the principles progressively (F-FAIR, F-A-FAIR, F-A-I-FAIR, F-A-I-R-FAIR the last being (a)).
If the group agree this then the minimalist approach (least number of elements required for asserting FAIRness for each principle) works.

Anticipating agreement in the group - or at least discussion aided by considering both possibilities of mapping elements to principles -  I'll work on that over the next couple of days (I have a lot of telcos today but will start on it in between).

best
Keith

**Comment by keithjeffery** [comment]
Makx -
I have done a first draft MINIMALIST specificaion quickly to move the discusstion along.  
[RDA MIG Elements to FAIR Principles 20190708 MINIMALIST.xlsx](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/files/3367053/RDA.MIG.Elements.to.FAIR.Principles.20190708.MINIMALIST.xlsx)
Attached.
best
Keith

**Comment by makxdekkers** [comment]
@keithjeffery Thanks for the new spreadsheet. If I understand correctly the non-blank cells indicate for which principle a metadata element is important. For example, it's true that you cannot talk about qualified references if resources don't have persistent and unique URIs. 

However, I would like to distinguish two issues here:

1. the choice of the element set, i.e. the minimum set of semantic descriptors to be provided for a dataset or other resource for which the FAIRness is evaluated
2. the choice of the principle(s) under which a particular metadata element is evaluated, i.e. where to put an indicator for a metadata element

For the first issue, you have brought forward a proposal to use the MIG set as a minimum requirement. This proposal needs to be discussed by the Working Group. As far as I can see, if the WG agrees, this would give us a first resolution of the issue "_what do we understand by **rich metadata**_", although there might be further discussion on what information needs to be provided as values for those elements (e.g. with respect to quality -- accuracy, completeness, etc.).

For the second issue, I would like to move the discussion to the most relevant principles, which I think are [F2](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/16), concerned with metadata for discovery, and [R1](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/26), concerned with metadata for reuse, with R1.1 and R1.2 giving further details on two specific aspects of metadata for re-use.

**Comment by keithjeffery** [comment]
Makx -

many thanks for the comments.

My 'minimalist' spreadsheet was meant to indicate in the non-blank cells the elements (rows) necessary for an evaluation of the principle delineated by the column.  I would welcome group discussion on this - and also on the 'maximalist' version which was meant to indicate the set of elements required to discharge the obligations intended by the principle delineated by the column - i.e. the elements needed for an autonomic system to utilise data (or other) assets FAIRly.  

It would be great if between this WG and MIG within RDA we could come to an agreed definition of rich metadata required for FAIR processing (maximalist) and for FAIR evaluation (minimalist).

Concerning your second point, you seem to be suggesting that any given element should be used only as an evaluator for one principle.  Your subsequent paragraph on your second point clearly argues against this since you choose F2 and R1 both of which essentially require a full set of elements to satisfy the 'rich metadata' or 'plurality of accurate and relevant attributes' criteria.  My personal view is that the presence of a value of approriate quality for each element (row) indicated within each principle (column) would provide the evidence for the indicator metric which could be Y/N, it could be 0 through 5 (a graded scale e.g. based on some aspects of quality) and so on.

To take a simple example: it would at first glance seem that F1 demands a Y/N answer. But we may wish to be more subtle and break this into (a) uniqueness on a scale of: within institutonal repository, global, universal; (b) persistence on a timescale of: seconds to years to infinite time (I guess no-one can guarantee eternity).  So - for simplicity - if both (a) and (b) had an arbitrary scale of 1-2-3 then a typical dataset might score (a) 2 (b) 2 on FAIRness for this principle.  The point I am making is that the presence of the ID is insufficient.  Its characteristics - or more accurately the support given by the surrounding environment somehow characterised - are also important and need to be measured to asses FAIRness.

It gets much more fun with other elements!

However,  I suggest we walk before we run.  Can we stimulate the WG to discus the spreadsheet(s) first to get a solid basis for evaluation of the principles?
best
Keith

**Comment by makxdekkers** [comment]
I'd like to quote @markwilkinson from https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/28#issuecomment-509920444: 

_"We need "a thick cloud" of metadata, but we cannot pre-determine what that cloud is composed of (and shouldn't try!)"_

This seems to be contrary to trying to agree on a fixed set of metadata elements that constitute 'rich metadata'.

Could an indicator for both F2 and R1 be 

**Provision of a suffient amount of metadata**

and then leave it to the evaluator to define whether the provided metadata is sufficient?

**Comment by SusannaSansone** [comment]
Why creating another set of metadata elements, or a mandatory mapping to it, if we have not done this for e.g. PROV in #28? 
For discoverability we have schema.org, or DC, DCAT etc. As detailed #29 and #26, for richer domain/discipline-specific level there are community standards that have already defined the minimal reporting metadata elements requirements, which outline the necessary and sufficient information vital for contextualizing and understanding a digital object. And this is especially true to represent and report datasets.

**Comment by makxdekkers** [comment]
@SusannaSansone I don't think it is the objective to create yet another metadata schema. The Metadata IG has offered a list of elements they think could be relevant.
Possibly the approach could be that, first of all, the domain/discipline-specific metadata standard/schema should be used, and, secondly, if such a domain-specific standard is not available, the set of Metadata IG elements could be considered as a general guideline. Not in the sense that the metadata needs to include information for all those elements, but that the list could be used as a guideline about which kinds of descriptors could be provided, if possible and relevant. 
Maybe there could be two indicators:

**1. Provision of a sufficient amount of metadata, following domain/discipline-specific metadata standard**

**2. If no domain/discipline-specific metadata standard is available, provide metadata for the elements defined by the RDA Metadata IG, as much as possible and relevant**

These could be either under F2 or R1.

**Comment by SusannaSansone** [comment]
@makxdekkers ok this " first of all, the domain/discipline-specific metadata standard/schema should be used" is indeed key, thanks for clarifying. On this matter you can point to the RDA FAIRsharing WG registry (https://fairsharing.org) for generic and domain/disciplines standards, since it is an approved/adopted RDA output.

**Comment by makxdekkers** [comment]
@SusannaSansone We can include a reference to the FAIRsharing registry in the indicators F2-01M (https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/16) and R1-01M (https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/26), adding to "_following domain/discipline-specific metadata data standard_": ".._.e.g. as listed in the FAIRsharing registry_".
Would that resolve your comment?

**Comment by DrMaggie** [comment]
I think we should avoid referencing specific initiatives (even if they are 'standards' or adopted (RDA) outputs) in any of the indicator/test "short definitions". IMHO, a much better place for such examples or clarifications would be in the accompanying documentation/description of each indicator - compare e.g. the GO-FAIR web pages for each of the FAIR principles (https://www.go-fair.org/fair-principles/f2-data-described-rich-metadata/). This approach makes it much easier to update the information, and also avoids problems caused by e.g. rebranding of the resources that are referred to.

**Comment by makxdekkers** [comment]
@DrMaggie Are you suggesting then to rephrase F2-02M (https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/16#issuecomment-517601938) and R1-02M (https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/26#issuecomment-517604325), removing the reference to the RDA Metadata IG from the short definitions and move it to example in the bullet points?
I am interested to hear other members' views.

**Comment by rwwh** [comment]
I'd like to followup on @keithjeffery 's excellent analysis of the "FAIR" **ladder**. The FAIR principles have both an aspect of attempted independence between the four letters, as well as a little sequential interdependence. Just as with a ladder, it makes sense to strengthen each step individually, and the individual FAIR guiding principles can help. But in the end, aiming for FAIR data can not be done without the **earlier** steps. One can make a data set more _interoperable_ with the world, but that makes it only truly more FAIR if it is also _findable_ and _accessible_.

In many cases the responsibilities for the letters can also be roughly split: the F and A are mainly properties of the repository, whereas I and R are mostly up to the researchers themselves.

**Comment by SusannaSansone** [comment]
> I think we should avoid referencing specific initiatives (even if they are 'standards' or adopted (RDA) outputs) in any of the indicator/test "short definitions". IMHO, a much better place for such examples or clarifications would be in the accompanying documentation/description of each indicator - compare e.g. the GO-FAIR web pages for each of the FAIR principles (https://www.go-fair.org/fair-principles/f2-data-described-rich-metadata/). This approach makes it much easier to update the information, and also avoids problems caused by e.g. rebranding of the resources that are referred to.

@DrMaggie that page also contains pointers to specific community metadata standards. Note that FAIRsharing is not a community standards but lists them, making them discoverable to many that have no idea what metadata standards for their community is.

**Comment by SusannaSansone** [comment]
> @SusannaSansone We can include a reference to the FAIRsharing registry in the indicators F2-01M (#16) and R1-01M (#26), adding to "_following domain/discipline-specific metadata data standard_": ".._.e.g. as listed in the FAIRsharing registry_".
> Would that resolve your comment?

@makxdekkers as I say in my reply to DrMaggie it helps to point people to lists of these domain/discipline-specific metadata data standards. Otherwise how we provide help, examples and guidance? This is the all reason why the RDA FAIRsharing WG was set up and has delivered a registry to help users to discover these wealth of domain/discipline-specific metadata data standards.

**Comment by makxdekkers** [comment]
@SusannaSansone Do you agree with my proposal to include a reference to the FAIRsharing registry as an example? 
If I understand @DrMaggie's point correctly, any reference to external resources may become outdated, and therefore we should be careful with such references.

**Comment by makxdekkers** [comment]
I'd like to point the members of the WG to a session at the 14th RDA plenary to discuss metadata issues around FAIR Data: https://www.rd-alliance.org/metadata-fair-data. The meeting will take place in Breakout 7 on 25 October 11:00-12:30 (Helsinki time). I am sure that the aspect of 'richness' will be discussed at this meeting.

**Comment by SusannaSansone** [comment]
> @SusannaSansone Do you agree with my proposal to include a reference to the FAIRsharing registry as an example?

Yes, especially as this is an RDA approved output.

> If I understand @DrMaggie's point correctly, any reference to external resources may become outdated, and therefore we should be careful with such references.

FAIRsharing itself also has a PID: https://doi.org/10.25504/FAIRsharing.2abjs5
