### ISSUE TITLE
Indicators for R1.3: (meta)data meet domain-relevant community standards	

### ISSUE THREAD

**Issue by makxdekkers** [RDA-FAIR/FAIR-data-maturity-model-WG#29]
![image](https://user-images.githubusercontent.com/7534601/60017879-20b69280-968a-11e9-94f6-8bddda503879.png)

**Comment by makxdekkers** [comment]
Points raised in online meeting 3 on 18 June 2019

- It was proposed that the indicator could refer to a schema rather than a template.

**Comment by keithjeffery** [comment]
For reusability there are (at least) two levels.  Primary reusability depends on a common (or conversion to comon) metadata element set (syntax, semantics) useful enough to determine if the asset is generally reusable so that, for example, a glaciologist could reuse some climate data.  Secondary reusability depends on conversion of heterogenous metadata schemas from different sub-domains within the same domain to provide detailed contextualised reuse of the assets together (e.g. glaciologist in Alpine region comparing rate of ice retreat with glaciologist from Himalayan region)

**Comment by makxdekkers** [comment]
@keithjeffery Good point.
In your view, would this lead to two indicators?

1. use of a 'common' (widely understood, like Dublin Core, DCAT or DataCite Kernel ) metadata element set, or at least a set of metadata properties that can be easily converted to a common one
2. use of a more detailed, domain-specific set for cross-sub-domain interoperability

Or could this be collapsed into one?

- use of a 'common' element set with domain-specific extensions

**Comment by keithjeffery** [comment]
Makx –
I am happy with either approach as long as the ‘’common element set’ is adequate for each of the principles of FAIR.
Best
Keith

--------------------------------------------------------------------------------
Keith G Jeffery Consultants
Prof Keith G Jeffery
E: keith.jeffery@keithgjefferyconsultants.co.uk<mailto:keith.jeffery@keithgjefferyconsultants.co.uk>
T: +44 7768 446088
S: keithgjeffery
----------------------------------------------------------------------------------------------------------------------------------
The contents of this email are sent in confidence for the use of the
intended recipient only.  If you are not one of the intended
recipients do not take action on it or show it to anyone else, but
return this email to the sender and delete your copy of it.
----------------------------------------------------------------------------------------------------------------------------------

**Comment by makxdekkers** [comment]
@keithjeffery Yes, the idea would be that the 'common set' meets the requirements across the various FAIR principles.

**Comment by micheldumontier** [comment]
here, it's important that every community specification is encoded in a manner that we can automatically check their compliance to a particular quality standard.  this means, as a first step, the community standard should be encoded in a language (xml schema, json schema, shacl, etc. ) that allows computational verification of 1) syntax, and 2) content expectations .

**Comment by RDA-FAIR** [comment]
![image](https://user-images.githubusercontent.com/47179213/60704336-713cb400-9f04-11e9-9fed-330b5170aa1a.png)

Here is a new version of the indicator!

**Comment by makxdekkers** [comment]
@micheldumontier Are you proposing to add an indicator for this principle that expresses these further requirements on the standard being used? 

E.g.

**R1.3-02 Community standard is encoded in machine-understandable language**
- No machine-understandable encoding
- Machine-understandable encoding (e.g. XML schema, JSON schema, SHACL etc.)

**Comment by micheldumontier** [comment]
I like this idea of metaformats as common denominators with wide tool support: https://www.w3.org/standards/webarch/metaformats
The second aspect, is that of validation languages e.g. json schema, xml schema, shacl, etc

**Comment by markwilkinson** [comment]
I think the discussion above reflects a bit of cart/horse/cart.  First, as Michel says, there are existing core standards(at a minimum, for metadata) that are well-established.  So cart/horse would be to first push the community into adopting these as their preferred standards, versus some other community-born standard.  Then horse/cart, the community members should be pushed to comply with these standards.  (this is, for me, the most primitive adherence to R1.3)

THEN, superimposed on that, we have other more community-specific standards ("real" R1.3).  One example we are dealing with in the Clinical Trials domain is that their community thinks that pre-registration of a clinical trial is an absolute must-have.  So we have to "coin" the predicate, and decide what it's value(s) will be... and then design a metric that tests, for this community, if the metadata record includes that property and a valid value.  

This is greatly facilitated if the horse (the metaformat) and the cart (the schema/validation language) are already decided for that community.

For data, it becomes very community-specific (i.e. not something a WG can make suggestions about), since data formats/contents are often selected for pragmatic reasons (like data size, or ease of processing)

**Comment by keithjeffery** [comment]
@Mark -
I would suggest each community needs to define the metadata elements suitable for them rathe than being pushed into adoptiing DC, DCAT etc.  Once the elements are defined they can choose the metadata format that is suitable (i.e. the one that matches best with or without application profiles as extensions).   By all means they should be encoded in a metaformat and Michel's list is a good start (and by the way there are in the real world much use of old metaformats such as relational DBms, object-oriented DBMS and so on which are perfectly adequate for richness of represntation, tend to have validation by schema and constraints and may be better at performance).

**Comment by makxdekkers** [comment]
It seems to me that the two indicators proposed above (R1.3-01 following community standard and R1.3-02 machine-understandable encoding) catch a big part of the discussions and the rough agreement between the contributors here. 
So, rather than mandating or recommending specific standards and encodings, leave it to the community to come up with the detailed specification of the metadata elements and data elements that make sense in the light of the potential reuse.
Or do you think that there could be additional indicators?

**Comment by keithjeffery** [comment]
@Makx -
R1.3-01 and R1.3-02 are a good start.  They ensure that ideally there is a schema (so there can be a syntax, possibly semantic check) and encourage moves to machine-understandability.  However, the principle requires 'domain relevant community standards' so the degree to which the metadata elements being considered match 'domain relevant community standards' is important - basically the closer they match the easier is re-use.  I suggest we need an indicator that measures exactly that - the closeness of match of the metadata being evaluated to one or more community standards covering both syntax and semantics.

**Comment by makxdekkers** [comment]
@keithjeffery I don't understand the additional indicator. In my mind, R1.3-01 already covers the 'closeness' of the metadata to the community standard -- the metadata either follows the community standard or it doesn't. Maybe it is the formulation of R1.3-01? Could it be:

**R1.3-01 (Meta)data follows a community standard** 
- (Meta)data **NOT** following community standard
- (Meta)data following community standard (e.g. based on a template)

**Comment by keithjeffery** [comment]
@Makx -
Apologies for lack of clarity.  I would suggest
R1.3-01 (Meta)data follows a community standard

(Meta)data NOT following community standard (e.g. based on a template or schema)
(Meta)data following community standard (e.g. based on a template or schema)

This brings back the template concept while preserving the schema concept - both of which would ndicate how closely the metadata elements relate to a community standard.

This together with exiting R1.3-02 seems appropriate to me

**Comment by SusannaSansone** [comment]
One comment first, and two suggestions on this.

**1.** This discussions links nicely with the content of the RDA FAIRsharing WG registry, which is now one of the formally approved RDA outputs.
 
**2.** We need to clarify what we mean for standards, templates and schemas I bet we have different definitions and understanding of these. 
Especially when looking beyond the generic standards (e.g. DC/DCAT, schema.org) and into domain/discipline-specific standards. [FAIRsharing](https://fairsharing.org), for example classifies community standards (for representing/reporting digital objects) in: (a) **_minimal reporting requirements_** (checklists or templates that outline the necessary and sufficient information vital for contextualizing and understanding a digital object), (b) **_terminologies_** (from CVs to ontologies that provide definitions and unambiguous identification for concepts and object) and (c) **_models/formats_** (define the structure and relationship of information for a conceptual model or schema, and include transmission formats to facilitate the exchange of data between different systems). Only terminologies and models/formats are machine readable and expressed in one or more metaformat (XML, DRF, TAB etc). 

**3.** Who does define what is a community standards or not, especially for the domain/data/discipline-specific one? The presence of some metadata elements e.g. in XML metaformat does not make me compliant to any community agreed standards.

**Comment by makxdekkers** [comment]
@SusannaSansone Would you want to propose additional indicators for this principle?

**Comment by RDA-FAIR** [comment]
Please find the current version of the indicator(s) and their respective maturity levels for this FAIR principle. Indicators and maturity levels will be presented, as they stand, to the next working group meeting for approval.  In the meantime, any comments are still welcomed.

The editorial team will now concentrate on weighing and prioritizing these indicators. More information soon.

![image](https://user-images.githubusercontent.com/47179213/62354956-544cce00-b50e-11e9-92f6-ce6b90188c26.png)

![image](https://user-images.githubusercontent.com/47179213/62354961-56af2800-b50e-11e9-9cdc-9eae654407b2.png)

**Comment by SusannaSansone** [comment]
> @SusannaSansone Would you want to propose additional indicators for this principle?

@makxdekkers the issue is the lack of clarity on what standards, templates and schemas are. Also saying XML schema is not enough; this is just a metaformat (as RDF, TAB etc) and for community standards (many models and formats) there are specific XML representations, eg. https://doi.org/10.25504/FAIRsharing.6cs4bf. In this case formatting analytical data in XML is not enough and not the same that making it compliant to AnIML, as in this example.

**Comment by makxdekkers** [comment]
@SusannaSansone Could you propose better wording for these indicators to meet your requirements?

**Comment by makxdekkers** [comment]
@SusannaSansone Maybe we could include a reference to the FAIRsharing registry in the examples for indicators R1. 3-01M/D to respond to your comment?

**Comment by SusannaSansone** [comment]
@makxdekkers yes, thanks; as said in  #13 at least we point people to a list of these domain/discipline-specific metadata data standards.

**Comment by makxdekkers** [comment]
Peter Wittenburg at https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit?disco=AAAADadg-WY

On R1.3-01D and R1.3-02D:
Here I disagree. Data science is dynamic and there must be the possibility to define new standards if needed, i.e. we need to allow for innovation.

**Comment by makxdekkers** [comment]
Peter, as far as I can see, nothing in the formulation of the principle or the indicators rules out the development and application of new standards for the publication and reuse of new science. 
If a new area of research emerges and a community is established around that area, wouldn't that community need to establish a common way of publishing results, and then also publish a specification that enables reusers to make sense of the results? 
Maybe the issue is with the word '_standard_' -- could we interpret that in a wide sense as including any published specification of models and schemas etc., not just in the narrow meaning of formal ISO standards, W3C recommendations etc?

**Comment by RDA-FAIR** [comment]
On the 19/08/2019, Mark D Wilkinson commented 

The requirement for using a community standard could be difficult to meet for new research, because it could be too early for standards to be established in that area. Could this be handled by understanding ‘standard’ in a wider sense, e.g. including less formal, published specifications?

> See above - if there isn't a standard, and the data representation could be standardized, then create and approve a standard (e.g. a Minimal info model)

Furthermore, a suggestion has been made to refer to the [FAIRsharing registry of community standards](https://fairsharing.org/standards/) in various places (in particular #16  and R1.3) to help people find relevant domain/discipline-specific metadata/data standards.

> +1 +1 +1!  And... beyond that... we should encourage FAIRsharing to expand the metadata elements that they provide for each standard, so that an agent discovering the standard in FAIRsharing is sufficient for it then to operate on the (meta)data itself (likely in collaboration with other, similar projects).  This will require resources for FAIRsharing!!  It's not an easy problem!  (one simple example is this:  My agent has a GUID.  I want to know if it conforms to an existing standard (e.g. DOI).  I would like to be able to find all GUID standards in FAIRsharing, and then do a test (e.g. regular expression) against my GUID, to see if it conforms with any of those - I discover that it pattern-matches with DOI.  Then I use the other metadata in FAIRsharing to determine what the resolution mechanism is for this GUID (https://doi.org/XXXXX  with the Accept headers "application/json").   Some of this is captured in the MIRIAM registry, but not all, and not at the level of granularity that FAIRsharing offers (or could offer!) - e.g. MIRIAM can tell me how to resolve an ID once it is identified, and even how to identify it by RegExp, but it cannot tell me if that is, in fact, a globally-accepted GUID standard.  

Read his comments here: https://www.rd-alliance.org/group/fair-data-maturity-model-wg/post/discussion-items-fair-data-maturity-model-19-august-2019

**Comment by makxdekkers** [comment]
@JolandaS wrote at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/30#issuecomment-535419649:
> R1.3-01M: community standards seems to be overlapping with R1-01M. What is the difference with domain/discipline standards?

Reply from @makxdekkers at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/30#issuecomment-536336554:

> There is indeed overlap between R1 and R1.3. The mention of 'sufficient metadata' in the indicator for R1 is to satisfy the requirement of "plurality and relevance of attributes" in the principle, while the indicators for R1.3 focus on the "standard" aspect. The word 'standard' does not appear in the definition for R1, but was added later based on comments in the meeting on 18 June 2019 (see also [#26 (comment)](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/26#issuecomment-504982246)) because the richness of metadata is dependent on the community.
> Would it be clearer if the text of the indicators were aligned to mention 'community standard' instead of 'domain/discipline-specific metadata standard' in R1?

**Comment by bahimc** [comment]
Dear contributors,
 
Below you can find the indicators and their maturity levels in their current state as a result of the above discussions and workshops.
 
![image](https://user-images.githubusercontent.com/47179213/66299645-34fa6480-e8f4-11e9-85a2-deede12e3d76.png)
![image](https://user-images.githubusercontent.com/47179213/66299646-375cbe80-e8f4-11e9-9210-c7e534c3f0d2.png)

 
**Please note that this thread is going to be closed**, within a short period of time.  The current state of the indicators, as of early October 2019, is now frozen, with the exception of the indicators for the principles that are concerned with ‘richness’ of metadata (F2 and R1). The current indicators will be used for the further steps of this WG, which are prioritisation and scoring.  Later on, they will be used in a testing phase where owners of evaluation approaches are going to be invited to compare their approaches (questionnaires, tools) against the indicators. The editorial team, in consultation with the Working Group, will define the best approach to test the indicators and evaluate their soundness. As such, the current set of indicators can be seen as an ‘alpha version’. In the first half of 2020, the indicators may be revised and improved, based on the results of the testing. **If you have any further comments, suggestions regarding that specific discussion, please share them with us. Besides, we invite you to have a look at the following two sets of issues.**
 
**Prioritisation**
 
[• Indicators prioritisation for Findability
](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/30)[• Indicators prioritisation for Accessibility](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/31)
[• Indicators prioritisation for Interoperability
](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/32)[• Indicators prioritisation for Reusability ](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/33)
 
**Scoring** 
 
[• Indicators for FAIRness | Scoring
](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/34) 
We thank you for your valuable input!

**Comment by ljgarcia** [comment]
> 
> 
> here, it's important that every community specification is encoded in a manner that we can automatically check their compliance to a particular quality standard. this means, as a first step, the community standard should be encoded in a language (xml schema, json schema, shacl, etc. ) that allows computational verification of 1) syntax, and 2) content expectations .

I would read @micheldumontier [comment above](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/29#issuecomment-508419888) as "community standards should be FAIR themselves" which seems fair. 

And, as @SusannaSansone [mentioned](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/29#issuecomment-519985391), they should be registered in FAIRsharing so it becomes a central point to find such community standards. FAIR community standards will make it easier to evaluate compliance to them. In order to make this evaluation easier, communities should also provide validation mechanisms. Maybe validators should also be registered in FAIRSharing. 

In this way, a digital object could claim compliance to community standard if their metadata/data passes the community validation. It would be responsibility of the digital object A to add a "validated stamp" or so regarding a community standard and, depending on the resources provided by the community, they could also register with that community and shown on their listed resources or so.
