### ISSUE TITLE
Indicators I2-01M+D: Out of scope 

### ISSUE THREAD

**Issue by makxdekkers** [RDA-FAIR/FAIR-data-maturity-model-WG#41]
These indicators test for the use of standard vocabularies:

I2-01M Metadata uses standard vocabularies
I2-01D Data uses standard vocabularies

It has been noted that FAIR principle I2 is only about _FAIRness_ of vocabularies and the aspect of _'standard'_ is never mentioned, so these indicators extend the FAIR principles.

This could be considered out of scope for the working group, and therefore the proposal is:

**Drop indicators I2-01M and I2-01D**

**Comment by andrasholl** [comment]
It is important that the vocabularies used are themselves FAIR. "Standard" in my reading is
stronger criteria: it means that the vocabulary in not only findable, accessible, interoperable
and reusable, but also widely used within the discipline. For the time being insisting on
Fairness of vocabularies might be enough.

**Comment by pmergen** [comment]
Based on discussions on this point within TDWG.org (Biodiversity Information Standards), we would like to stress, that even if it is not as such in the definition of FAIR, for the indicator of vocabularies, the term standards needs to stay in. Just vocabularies without any standardization, or being approved controlled vocabularies with consistence, will maybe be findable and accessible, but hardly interoperable and re-usable as going in all directions. Especially if it should be used as an indicator to check if something is FAIR or not, some agreed standard metrics should be there so that it remains comparable and measurable.  we would thus advocate to keep standard into scope.

**Comment by makxdekkers** [comment]
@pmergen I understand that standardisation is important. However, the question is not whether this is good or not, but whether this is required by the FAIR principle. We need to keep in mind that our charter is not to improve on the FAIR principles but to apply them.
@markwilkinson, @susannaSansone, @rwwh, @micheldumontier?

**Comment by andrasholl** [comment]
Hi,

Just as you say, FAIRness of a vocabulary involves Interoperability, Reusability, so implicitly contain
standardisation. While one could argue, that FAIRness and standardness is not absolutely the same,
for me, those concepts overlap enough. And FAIRness is more: earlier I argued that applying a standard
vocabulary is not enough, one should specify which vocabulary is used. I think FAIRness covers this
aspect as well.

Cheers, Andras Holl 

----- Original Message -----

**Comment by makxdekkers** [comment]
@andrasholl Do I understand correctly that you agree with the proposal to drop the indicators  _I2-01M+D: (Meta)data uses standard vocabularies_?

**Comment by andrasholl** [comment]
Yes. I2-01M+D could be dropped. I2-02M+D could be promoted to "recommended".

----- Original Message -----

**Comment by micheldumontier** [comment]
R1.3 makes it clear: (Meta)data meet domain-relevant community standards ; so FAIR vocabularies are expected to be formulated in a manner that are identifiable, accessible, formal, machine-readable, (etc), and that these practices are established by communities (e.g. W3C established OWL for ontologies, RDF(S)/SKOS, for vocabularies etc).
