### ISSUE TITLE
Downgrade priority of F1-01D Data is identified by a persistent identifier from Essential to Important

### ISSUE THREAD

**Issue by makxdekkers** [RDA-FAIR/FAIR-data-maturity-model-WG#53]
Testers suggested that it is not always realistic to expect that data has a persistent identifier.

**Comment by rwwh** [comment]
I noted that a similar proposal for F1-01M (PID for the metadata) was NOT getting a majority and is therefore not brought into discussion. I would like to argue that these two should get the same priority. If there is a real reason why a PID for metadata should have a higher priority than a PID for data, I am open to be convinced. I think at this point a PID for data is a lot more common than having a PID for metadata (although the FAIRness of the semantics for that PID, often a DOI, can still be discussed).

**Comment by rwwh** [comment]
I'd argue that F1-01D should be essential. If people are now reasoning that currently not all data gets a PID, I think that is the wrong reasoning. Note that the FAIR principles were born from the realisation that something needs to change, not to describe the status quo. I think it is rarely hard to give data a PID now, and having this indicator at _essential_ prioritiy level is a nice incentive to pursue that. 

I am open to be convinced otherwise.
